### ISSUE TITLE
Media is not displayed when both image and video are attached

### ISSUE THREAD

**Issue by eiurur** [eiurur/Mukuu#144]
imageとvideoの複合的な添付に対応していない

```
vue.runtime.esm.js:3049 TypeError: Cannot read properties of undefined (reading 'variants')
    at a.video (Video.vue:50:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at a.video (vue.runtime.esm.js:5537:25)
    at a.Lt (Video.vue:1:184)
    at En.e._render (vue.runtime.esm.js:2684:28)
    at a.i (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
    at new e (vue.runtime.esm.js:3436:51)
    at Ni (vue.runtime.esm.js:3892:5)
```

![brave_DZOpka3nnh](https://github.com/user-attachments/assets/b2cf21b1-4026-463e-8764-5d84dda32779)

**Comment by eiurur** [comment]
imageかvideoで表示コンポーネントを分岐させるのやめた。
mediaをループさせてtypeプロパティの値をみて表示すべきタグの判定を行う
![brave_ev5KXhtLoI](https://github.com/user-attachments/assets/32e3c0b7-6210-4987-8749-b5c370b3f648)
